version: '3'
services:
  app:
    build: .
    depends_on:
      - redis
    command: gunicorn -w 2 -b 0.0.0.0:5000 app:app

  redis:
    image: redis:latest
    ports:
      - '6379:6379'

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:rw
    depends_on:
      - app
    ports:
      - 80:80
