on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-deploy-frontend-prod:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: calculator-miluim
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: il-central-1
      - uses: actions/setup-node@v2

      - name: Build Frontend Dist
        env:
          VITE_BASE_URL: ${{ secrets.API_GATEWAY_PROD_URL }}
        run: |
          ./build/build_frontend.sh

      - name: Upload Dist to PROD bucket and update CDN cache
        run: |
          aws s3 rm s3://calculate-miluim.info/ --recursive
          aws s3 cp ../dist s3://calculate-miluim.info/ --recursive
          aws cloudfront create-invalidation --distribution-id E326TPQZUHJ20N --paths '/*'

          
