on:
  workflow_dispatch:

jobs:
  build-deploy-lambda:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: calculator-miluim
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: il-central-1

      - run: ./build/build_app_image_staging.sh